### ISSUE TITLE
[develop] Erreur avec saveToCassandra()

### ISSUE THREAD

**Issue by ghost** [t3g7/spark-streaming-twitter#1]
Un `./spark-submit` de l'app provoque cette erreur :

```
15/11/08 09:07:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform...  using builtin-java classes where applicable
15/11/08 09:07:19 WARN MetricsSystem: Using default name DAGScheduler for source because  spark.app.id is not set.
Exception in thread "main" java.lang.NoSuchMethodError:  scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$Ja vaMirror;
    at Streamer$.main(Streamer.scala:34)
    at Streamer.main(Streamer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by ghost** [comment]
Ca fonctionne avec le shell : https://stackoverflow.com/questions/25837436/how-to-load-spark-cassandra-connector-in-the-shell

**Comment by ghost** [comment]
J'ai posé la question sur StackOverflow : https://stackoverflow.com/questions/33724165/nosuchmethoderror-with-spark-cassandra-connector

**Comment by ghost** [comment]
Scala 2.11 pas compatible --> scala 2.10 à utiliser
